# .github/workflows/main.yml

name: Deploy to Cloudflare Workers

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      # Step 1: Check out the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Deploy the worker using the official Wrangler action
      # This action automatically handles authentication via the GitHub App.
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          # Use 'with' to pass inputs directly to the action
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
